widgets_Array = Array
    .hover = Mean.
widgets_AutoThreshold = Auto
    .hover = Auto threshold
widgets_CheckAll = Check all
    .hover = Check all items in array.
widgets_DeltaDegreesOfFreedom = Delta degrees of freedom
    .abbreviation = DDOF
    .hover = Delta degrees of freedom.
widgets_FilterThreshold = Filter
    .hover = Filter threshold
widgets_IsAutoThreshold = Is auto
    .hover = Is auto threshold
widgets_ManualThreshold = Manual
    .hover = Manual threshold
widgets_Mean = Mean
    .hover = Mean.
widgets_Operator = Operator
    .hover = Operator
widgets_Percent = Percent
    .hover = Percent.
widgets_Precision = Precision
    .hover = Precision.
widgets_RelativeStandardDeviation = Relative standard deviation
    .abbreviation = RSD
    .hover = Relative standard deviation.
widgets_Significant = Significant
    .hover = Significant.
widgets_Sort = Sort
    .hover = Sort items in array.
widgets_SortByMinorMajor = Sort
    .hover = Sort by minor major
widgets_StandardDeviation = Standard deviation
    .abbreviation = SD
    .hover = Standard deviation.
widgets_UncheckAll = Uncheck all
    .hover = Uncheck all items in array.