Widgets_Array = Array
    .hover = Mean.
Widgets_AutoThreshold = Auto
    .hover = Auto threshold
Widgets_CheckAll = Check all
    .hover = Check all items in array.
Widgets_DeltaDegreesOfFreedom = Delta degrees of freedom
    .abbreviation = DDOF
    .hover = Delta degrees of freedom.
Widgets_FilterThreshold = Filter
    .hover = Filter threshold
Widgets_IsAutoThreshold = Is auto
    .hover = Is auto threshold
Widgets_ManualThreshold = Manual
    .hover = Manual threshold
Widgets_Mean = Mean
    .hover = Mean.
Widgets_Operator = Operator
    .hover = Operator
Widgets_Percent = Percent
    .hover = Percent.
Widgets_Precision = Precision
    .hover = Precision.
Widgets_RelativeStandardDeviation = Relative standard deviation
    .abbreviation = RSD
    .short = Relative
    .hover = Relative standard deviation.
Widgets_Significant = Significant
    .hover = Significant.
Widgets_Sort = Sort
    .hover = Sort items in array.
Widgets_SortByMinorMajor = Sort
    .hover = Sort by minor major
Widgets_StandardDeviation = Standard deviation
    .abbreviation = SD
    .hover = Standard deviation.
Widgets_UncheckAll = Uncheck all
    .hover = Uncheck all items in array.

Widgets_Relative = Relative
    .hover = Relative standard deviation.
Widgets_Absolute = Absolute
    .hover = Absolute standard deviation.
Widgets_Order = Order
Widgets_ByKey = By key
    .hover = Sort by key.
Widgets_ByValue = By value
    .hover = Sort by value.
Widgets_Ascending = Ascending
    .hover = Direct order (from min to max).
Widgets_Descending = Descending
    .hover = Reverse order (from max to min).

Widgets_Zero = Zero
    .hover = Highlight values equal to zero.
Widgets_Filter = Filter
    .hover = Filter values equal to zero.