Widgets_Threshold_Auto = Auto
    .hover = Auto threshold.
Widgets_Threshold_Kind = Kind
    .hover = Threshold kind.
Widgets_Threshold_Manual = Manual
    .hover = Manual threshold.
Widgets_Threshold_Filter = Filter
    .hover = Filter threshold.
Widgets_Action = Action
    .hover = Highlight sort or filter action.

Widgets_Array = Array
    .hover = Array.
Widgets_CheckAll = Check all
    .hover = Check all items in array.
Widgets_DeltaDegreesOfFreedom = Delta degrees of freedom
    .abbreviation = DDOF
    .hover = Delta degrees of freedom.
Widgets_Mean = Mean
    .hover = Mean.
Widgets_Operator = Operator
    .hover = Operator.
Widgets_Percent = Percent
    .hover = Percent.
Widgets_Precision = Precision
    .hover = Precision.
Widgets_Kind = Kind
    .hover = Standard deviation kind (absolute or relative).
Widgets_RelativeStandardDeviation = Relative standard deviation
    .abbreviation = RSD
    .short = Relative
    .hover = Relative standard deviation.
Widgets_Significant = Significant
    .hover = Significant.
Widgets_Sort = Sort
    .hover = Sort items in array.
Widgets_SortByMinorMajor = Sort
    .hover = Sort by minor major.
Widgets_StandardDeviation = Standard deviation
    .abbreviation = SD
    .hover = Standard deviation.
Widgets_UncheckAll = Uncheck all
    .hover = Uncheck all items in array.

Widgets_Relative = Relative
    .hover = Relative standard deviation.
Widgets_Absolute = Absolute
    .hover = Absolute standard deviation.
Widgets_Order = Order
Widgets_ByKey = By key
    .hover = Sort by key.
Widgets_ByValue = By value
    .hover = Sort by value.
Widgets_Ascending = Ascending
    .hover = Direct order (from min to max).
Widgets_Descending = Descending
    .hover = Reverse order (from max to min).

Widgets_ThresholdZero = Threshold zero
    .hover = Threshold values equal to zero.
Widgets_Highlight = Highlight
    .hover = Highlight values that are less than the threshold.
Widgets_Filter = Filter
    .hover = Filter values that are less than the threshold.


Widgets_CommaSeparatedValues = Comma-separated values
    .abbreviation = CSV
Widgets_RustyObjectNotation = Rusty Object Notation
    .abbreviation = RON
Widgets_Markdown = Markdown
    .abbreviation = MD
Widgets_Excel = Excel
    .long = Microsoft Excel
    .abbreviation = XLSX

Widgets_Legend = Legend
    .hover = Show the plot legend.
Widgets_RadiusOfPoints = Radius of points
    .hover = The radius of the points on the plot.
Widgets_Drag = Drag
    .hover = Enable dragging for the plot.
Widgets_Scroll = Scroll
    .hover = Enable scrolling for the plot.
